language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

script:
  - go test -v -coverprofile=coverage.out -covermode=count ./...

before_script:
  - go env

after_success:
  - go get -v github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
